name: "Deployment Workflow"
on:
  push:
    branches:
    - main

jobs:
  tests_deployment:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkouts out"
      uses: actions/checkout@v4


    - name: "Build the image"
      run: |
        docker build -t onlysalam/booksfinder:1


    - name: "LOGIN TO DOCKERHUB"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: "push to docker hub"
      run: |
        docker push onlysalam/booksfinder:1

    - name: "Setup AWS"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
